CREATE TABLE USER (
    ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE PARENT (
    ID INT PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES USER(ID) ON DELETE CASCADE
);

CREATE TABLE CHILD (
    CID INT NOT NULL,
    PID INT NOT NULL,
    ID INT NOT NULL,
    PRIMARY KEY (PID, CID),
    FOREIGN KEY (ID) REFERENCES USER(ID) ON DELETE CASCADE,
    FOREIGN KEY (PID) REFERENCES PARENT(ID) ON DELETE CASCADE
);


CREATE TABLE PAYMENT (
    PAYMENT_ID INT PRIMARY KEY,
    PARENT_ID INT NOT NULL,
    CHILD_ID INT NOT NULL,
    PAYMENT_AMNT DECIMAL(10,2) NOT NULL CHECK (PAYMENT_AMNT >= 0),
    PARENT_CARD_NUM VARCHAR(20),
    CHILD_CARD_NUM VARCHAR(20),
    PAYMENT_DATE DATE DEFAULT (CURRENT_DATE),
    FOREIGN KEY (PARENT_ID) REFERENCES PARENT(ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_ID, CHILD_ID) REFERENCES CHILD(PID, CID) ON DELETE CASCADE
);

CREATE TABLE CHORE (
    CHORE_ID INT PRIMARY KEY,
    PARENT_ID INT NOT NULL,
    CHILD_ID INT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    REWARD_AMNT DECIMAL(10,2) NOT NULL CHECK (REWARD_AMNT >= 0),
    STATUS VARCHAR(50),
    FOREIGN KEY (PARENT_ID) REFERENCES PARENT(ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_ID, CHILD_ID) REFERENCES CHILD(PID, CID) ON DELETE CASCADE
);